#!/bin/bash
INTERPRETER=$(pipenv --py)3.6m
CURRENT_USER=$(whoami)
CURRENT_DIR=$(pwd)
cd ./chomper && sudo ${INTERPRETER} ${CURRENT_DIR}/chomper/block.py --rule=$1 --block_length=$2 --settings_json_path=${CURRENT_DIR}/data/block_settings.json --reset_command "env PATH=${PATH} ${INTERPRETER} ${CURRENT_DIR}/chomper/reset.py"
